//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ServiceTest.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;s:Envelope xmlns:s=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///   &lt;s:Body&gt;
        ///      &lt;s:Fault&gt;
        ///         &lt;faultcode&gt;s:Client&lt;/faultcode&gt;
        ///         &lt;faultstring xml:lang=&quot;ar-SA&quot;&gt;Fault Reason&lt;/faultstring&gt;
        ///         &lt;detail&gt;
        ///            &lt;ExceptionContract xmlns=&quot;http://schemas.datacontract.org/2004/07/WcfService1&quot; xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///               &lt;ErrMsg&gt;grater than 5&lt;/ErrMsg&gt;
        ///            &lt;/ExceptionContract&gt;
        ///         &lt;/detail&gt;
        ///      &lt;/s:Fault&gt;
        ///   &lt;/s:Body&gt;
        ///&lt;/s:Envelo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string err1 {
            get {
                return ResourceManager.GetString("err1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;s:Envelope xmlns:s=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///   &lt;s:Body&gt;
        ///      &lt;s:Fault&gt;
        ///         &lt;faultcode&gt;s:OSB-0003&lt;/faultcode&gt;
        ///         &lt;faultstring&gt;s:Client&lt;/faultstring&gt;
        ///         &lt;detail&gt;
        ///            &lt;fault xmlns=&quot;http://eservices.momra.gov.sa/momra/commonTypes/version/1/messages&quot;&gt;
        ///               &lt;errorCode&gt;s:Client&lt;/errorCode&gt;
        ///               &lt;errorMessage&gt;Invalid Inputs.&lt;/errorMessage&gt;
        ///               &lt;errorType&gt;&apos;Routing To External Service Error&apos;&lt;/errorType&gt;
        ///               &lt;details&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string err2 {
            get {
                return ResourceManager.GetString("err2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;fault
        ///	xmlns=&quot;http://eservices.momra.gov.sa/momra/commonTypes/version/1/messages&quot;&gt;
        ///	&lt;errorCode&gt;s:Client&lt;/errorCode&gt;
        ///	&lt;errorMessage&gt;Invalid Inputs.&lt;/errorMessage&gt;
        ///	&lt;errorType&gt;&apos;Routing To External Service Error&apos;&lt;/errorType&gt;
        ///	&lt;details&gt;
        ///		&lt;detail
        ///			xmlns=&quot;&quot;&gt;
        ///			&lt;SamisNPVError
        ///				xmlns=&quot;http://schemas.datacontract.org/2004/07/SamisObjectModel&quot;
        ///				xmlns:i=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///				&lt;ErrorCode&gt;999&lt;/ErrorCode&gt;
        ///				&lt;ErrorType&gt;Functional&lt;/ErrorType&gt;
        ///				&lt;SamisWSFault&gt;
        ///					&lt;GroupErrorRes&gt;
        ///		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string err3 {
            get {
                return ResourceManager.GetString("err3", resourceCulture);
            }
        }
    }
}
